In [1]:
2 + 3

5

In [83]:
5 - 4

1

In [84]:
3 ** 2

9

In [87]:
a = 8
b = 5
c = a - b
print(' a - b is ', c)

 a - b is  3


In [ ]:
print('hello world')
print('My name is Eshwar'+ b

In [ ]:
a = 20

In [ ]:
b = 30

In [ ]:
c = a  + b

In [ ]:
print('The value of a + b is ', c)

In [ ]:
def donothing(x): 
    return x

donothing(5)

In [ ]:
donothing(10)

In [ ]:
help(len)  #  Python has a built-in help() function

In [ ]:
len?

In [ ]:
L = [1, 2, 3]
L.insert?
L?

In [ ]:
def square(a):       # Python’s triple-quote notation for multiline strings
            """Return the square of a."""
            return a ** 2
square?
square??

In [ ]:
square?    # 

In [ ]:
square??   # reading the source code of the object you’re curious about

In [ ]:
L.c        # L.clear  L.copy   L.count - put cursor after 'c'and enter 'tab'

In [ ]:
from itertools import co                 # tab after co

In [ ]:
import                      # tab to get the list of import objects - Display all 399 possibilities? (y or n) 

In [38]:
 *Warning?           #IPython provides a means of wildcard matching for names using the * character. 

In [39]:
 str.*find*?    # a string method that contains the word find somewhere in its name

Ctrl-a Move cursor to the beginning of the line 
Ctrl-e Move cursor to the end of the line 
Ctrl-b (or the left arrow key) Move cursor back one character 
Ctrl-f (or the right arrow key) Move cursor forward one character

Text Entry Shortcuts:

While everyone is familiar with using the Backspace key to delete the previous character, reaching for the key often requires some minor finger gymnastics, and it only deletes a single character at a time. In IPython there are several shortcuts for removing some portion of the text you’re typing. The most immediately useful of these are the commands to delete entire lines of text. You’ll know these have become second nature if you find yourself using a combination of Ctrl-b and Ctrl-d instead of reaching for the Backspace key to delete the previous character!
                

Keystroke Action 
Backspace key -Delete previous character in line 
Ctrl-d -Delete next character in line 
Ctrl-k -Cut text from cursor to end of line 
Ctrl-u- Cut text from beginning fo line to cursor 
Ctrl-y -Yank (i.e., paste) text that was previously cut 
Ctrl-t -Transpose (i.e., switch) previous two characters 

In [48]:
 %timeit  
L = [n ** 2 for n in range(1000)] 

In [47]:
%%timeit  
L = [n ** 2 for n in range(1000)]

787 µs ± 7.19 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [52]:
%timeit?
L = [n ** 2 for n in range(1000)]

In [53]:
%magic  # IPython's 'magic' functions

In [54]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [71]:
import math # We’ve imported the built-in math package, then computed the sine and the cosine of the number 2. 
math.sin(0)
math.cos(0)

1.0

In [66]:
math.cos(0) 

1.0

In [ ]:
print(In) 

In [ ]:
Out 

In [73]:
%history

def donothing(x): 
    return x
donothing(10)
def donothing(x): 
    return x

donothin(5)
def donothing(x): 
    return x

donothing(5)
help(len)
help(len)  #  Python has a built-in help() function
len?
len ?
len?
L = [1, 2, 3]
L.insert?
L = [1, 2, 3]
L.insert?
 L?
L = [1, 2, 3]
L.insert?
 L?
L = [1, 2, 3]
L.insert?
L?
 def square(a):  ....:     
            """Return the square of a."""
 def square(a):       
            """Return the square of a."""
 def square(a):       
            """Return the square of a."""
 def square(a):       
            """Return the square of a."""
            return a ** 2
square?
square??
 L.<TAB>
L = [1, 2, 3]
L.<TAB>
L = [1, 2, 3]
L.<>
L = [1, 2, 3]
L.<all>
square??   # reading the source code of the object you’re curious about
 def square(a):       # Python’s triple-quote notation for multiline strings
            """Return the square of a."""
            return a ** 2
square?    #
square??   # reading the source code of the object you’re curious ab

In [78]:
print(In[5]) 

help(len) 


In [79]:
print(Out[2]) 

10


In [81]:
 Out[2] ** 2 + Out[2] ** 2

200

In [88]:
 print(_)                     # simple shortcut for accessing previous output

9


In [89]:
print(___)                      #  double underscore to access the second-to-last output

5


In [92]:
Out[2]                          # same as - print(Out[2]) 

10

In [93]:
_2                              # same as - print(Out[2]) 

10

In [95]:
 math.sin(2) + math.cos(2); # Note that the result is computed silently, and the output is neither displayed 
                            # on the screen or stored in the Out dictionary:

0.4931505902785393

In [96]:
14 in Out            # False

False

In [97]:
%history -n 1-4               # For accessing a batch of previous inputs at once

   1:
def donothing(x): 
    return x
   2: donothing(10)
   3:
def donothing(x): 
    return x

donothin(5)
   4:
def donothing(x): 
    return x

donothing(5)


In [99]:
echo "hello world"   # Python SHELL COMMANDS

"hello world" 


In [100]:
pwd                  # present working directory

'C:\\Users\\Eshwar'

In [101]:
ls                    # ls = list working directory contents 

 Volume in drive C is OS
 Volume Serial Number is 104F-939A

 Directory of C:\Users\Eshwar

05-06-2019  01:56 PM    <DIR>          .
05-06-2019  01:56 PM    <DIR>          ..
25-05-2019  02:21 PM    <DIR>          .anaconda
05-06-2019  01:56 PM    <DIR>          .conda
05-06-2019  01:06 PM                77 .condarc
05-06-2019  01:08 PM    <DIR>          .ipynb_checkpoints
25-05-2019  02:24 PM    <DIR>          .ipython
25-05-2019  03:47 PM    <DIR>          .jupyter
02-06-2019  04:05 PM    <DIR>          .keras
25-05-2019  02:24 PM    <DIR>          .matplotlib
01-06-2019  12:00 AM                25 .python_history
02-06-2019  01:11 PM    <DIR>          .spyder-py3
25-05-2019  05:45 PM    <DIR>          3D Objects
25-05-2019  02:19 PM    <DIR>          Anaconda3
28-05-2019  01:01 PM    <DIR>          ansel
25-05-2019  05:45 PM    <DIR>          Contacts
02-06-2019  10:12 AM    <DIR>          Desktop
01-06-2019  12:07 AM    <DIR>          Documents
05-06-2019  01:03 PM    <DIR>        

In [102]:
cd projects/                    # cd = change directory

[WinError 3] The system cannot find the path specified: 'projects/ # cd = change directory'
C:\Users\Eshwar


In [114]:
contents = !ls

In [108]:
print(contents) 

["'ls' is not recognized as an internal or external command,", 'operable program or batch file.']


In [115]:
directory = !pwd
print(directory) 

["'pwd' is not recognized as an internal or external command,", 'operable program or batch file.']


In [116]:
message = "hello from Python"              # Communication in the other directio
!echo {message}

hello from Python 


In [117]:
 %cd ..

C:\Users


In [119]:
cd Eshwar   # page 37

C:\Users\Eshwar


In [128]:
def func1(a, b):           
    return (a / b)
 
def func2(x):           
    a = x           
    b = x - 1           
    return func1(a, b)
func2(2)

2.0

In [129]:
%xmode Plain     # Exception reporting mode: Plain

Exception reporting mode: Plain


In [130]:
func2(1)

ZeroDivisionError: division by zero

In [131]:
 %xmode Verbose        

Exception reporting mode: Verbose


In [132]:
%debug

> <ipython-input-128-d759aca45084>(2)func1()
      1 def func1(a, b):
----> 2     return (a / b)
      3 
      4 def func2(x):
      5     a = x

ipdb> 3
3
ipdb> 5
5
ipdb> 4
4
ipdb> quit


In [134]:
%timeit sum(range(100))   # %%timeit can be used to time the repeated execution of snippets of code:

2.65 µs ± 3.87 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [135]:
 %%timeit        #  %timeit will automatically adjust and perform fewer repetitions:
    total = 0       
    for i in range(1000):           
        for j in range(1000):               
            total += i * (-1) ** j


977 ms ± 5.09 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [136]:
import random       
L = [random.random() for i in range(100000)]       
%timeit L.sort()

1.14 ms ± 70.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [137]:
#  %time magic function may be a better choice. It also is a good choice for longer-running commands
import random       
L = [random.random() for i in range(100000)]       
print("sorting an unsorted list:")       
%time L.sort()

sorting an unsorted list:
Wall time: 21.8 ms


print("sorting an already sorted list:")       
%time L.sort()

In [139]:
def sum_of_lists(N):           
    total = 0           
    for i in range(5):               
        L = [j ^ (j >> i) for j in range(N)]               
        total += sum(L)           
        return total 

In [140]:
%prun sum_of_lists(1000000) 

    NumPy (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers. 
    In some ways, NumPy arrays are like Python’s built-in list type, but NumPy arrays provide much more efficient storage
    and data operations as the arrays grow larger in size. NumPy arrays form the core of nearly the entire ecosystem of 
    data science tools in Python, so time spent learning to use NumPy effectively will be valuable no matter what aspect 
    of data science interests you.


In [141]:
import numpy       
numpy.__version__


'1.16.2'

In [142]:
 import numpy as np 

In [ ]:
np.                    # press <TAB> after the . to see the ist of commands

In [143]:
np?                    #  NumPy’s built-in documentation, you can use this:

In [147]:
result = 0 
for i in range(4):    #This will add the numbers from 1 till 3 (4-1=3)
    result += i
print(result)

10


In [ ]:
A Python List Is More Than Just a List :
    Let’s consider now what happens when we use a Python data structure that holds many Python objects. 
    The standard mutable multielement container in Python is the list. We can create a list of integers as follows:


In [149]:
L = list(range(10))        # output is: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
L


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [150]:
type(L[0])    # int

int

In [151]:
L2 = [str(c) for c in L]          # ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
L2 

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [152]:
 type(L2[0])    # str

str

In [154]:
#  we can even create heterogeneous lists:
L3 = [True, "2", 3.0, 4]      
[type(item) for item in L3]


[bool, str, float, int]

In [155]:
# Fixed-Type Arrays in Python 

import array                   # array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
L = list(range(10))       
A = array.array('i', L)       
A                              # Here 'i' is a type code indicating the contents are integers. 

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
import numpy as np
np.array([1, 4, 2, 5, 3])    # array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [157]:
np.array([3.14, 4, 2, 3])    # array([3.14, 4.  , 2.  , 3.  ])

array([3.14, 4.  , 2.  , 3.  ])

In [158]:
np.array([1, 2, 3, 4], 
dtype='float32')                       # array([1., 2., 3., 4.], dtype=float32)

# If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:

array([1., 2., 3., 4.], dtype=float32)

In [159]:
 # nested lists result in multidimensional arrays        
np.array([range(i, i + 3) for i in [2, 4, 6]])
#array([[2, 3, 4],
#       [4, 5, 6],
#       [6, 7, 8]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating Arrays from Scratch Especially for larger arrays, it is more efficient to create arrays from scratch using 
routines built into NumPy. Here are several examples:


In [160]:
# Create a length-10 integer array filled with zeros        
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])