In [2]:
#conda install -c pytorch pytorch-cpu

In [3]:
import torch 

In [4]:
# Create a Tensor with just ones in a column
a = torch.ones(5)
 
# Print the tensor we created
print(a)
 
# tensor([1., 1., 1., 1., 1.])
 
# Create a Tensor with just zeros in a column
b = torch.zeros(5)
print(b)
 
# tensor([0., 0., 0., 0., 0.])

tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0.])


In [5]:
# We can similarly create Tensor with custom values as shown below
c = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])
print(c)
 
# tensor([1., 2., 3., 4., 5.])

tensor([1., 2., 3., 4., 5.])


In [6]:
# In all the above cases, we have created vectors or Tensors of dimension 
# 1. Now, let’s create some tensors of higher dimension.

d = torch.zeros(3,2)
print(d)
 
# tensor([[0., 0.],
#        [0., 0.],
#        [0., 0.]])

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [7]:
e = torch.ones(3,2)
print(e)
 
# tensor([[1., 1.],
#        [1., 1.],
#        [1., 1.]])

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [8]:
f = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(f)
 
# tensor([[1., 2.],
#        [3., 4.]])

tensor([[1., 2.],
        [3., 4.]])


In [9]:
# 3D Tensor
g = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(g)
 
# tensor([[[1., 2.],
#         [3., 4.]],
#
#        [[5., 6.],
#         [7., 8.]]])

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [10]:
# We can also find out the shape of a Tensor using .shape method.

print(f.shape)
# torch.Size([2, 2])
 
print(e.shape)
# torch.Size([3, 2])
 
print(g.shape)
# torch.Size([2, 2, 2])

torch.Size([2, 2])
torch.Size([3, 2])
torch.Size([2, 2, 2])


In [11]:
# Access an element in Tensor
# Now that we have created some tensors, let’s see how we can access an element in a Tensor. 
# First let’s see how to do this for 1D Tensor aka vector.

# Get element at index 2
print(c[2])
 
# tensor(3.)

tensor(3.)


In [12]:
# What about 2D or 3D Tensor? Recall what we mentioned about dimension of a tensor in last section. 
# To access one particular element in a tensor, we will need to specify indices equal to the dimension of the tensor. 
# That’s why for tensor c we only had to specify one index.

# All indices starting from 0
 
# Get element at row 1, column 0
print(f[1,0])
# We can also use the following
print(f[1][0])
 
# tensor(3.)
 
# Similarly for 3D Tensor
print(g[1,0,0])
print(g[1][0][0])
 
# tensor(5.)

tensor(3.)
tensor(3.)
tensor(5.)
tensor(5.)


In [14]:
# But what if you wanted to access one entire row in a 2D Tensor? 
# We can use the same syntax as we would use in NumPy Arrays.

# All elements
print(f[:])
 
# All elements from index 1 to 2 (inclusive)
print(c[1:3])
 
# All elements till index 4 (exclusive)
print(c[:4])
 
# First row
print(f[0,:])
 
# Second column
print(f[:,1])

tensor([[1., 2.],
        [3., 4.]])
tensor([2., 3.])
tensor([1., 2., 3., 4.])
tensor([1., 2.])
tensor([2., 4.])


## Specify data type of elements

Whenever we create a tensor, PyTorch decides the data type of the elements of the tensor such that the data type can cover all the elements of the tensor. We can override this by specifying the data type while creating the tensor.

In [15]:
int_tensor = torch.tensor([[1,2,3],[4,5,6]])
print(int_tensor.dtype)
 
# torch.int64
 
# What if we changed any one element to floating point number?
int_tensor = torch.tensor([[1,2,3],[4.,5,6]])
print(int_tensor.dtype)
 
# torch.float32
 
print(int_tensor)
 
# tensor([[1., 2., 3.],
#        [4., 5., 6.]])

torch.int64
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.int32
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [17]:
# This can be overridden as follows
int_tensor = torch.tensor([[1,2,3],[4.,5,6]], dtype=torch.int32)
print(int_tensor.dtype)
 
# torch.int32
 
print(int_tensor)
 
# tensor([[1, 2, 3],
#        [4, 5, 6]], dtype=torch.int32)

torch.int32
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


## CPU v/s GPU Tensor

PyTorch has different implementation of Tensor for CPU and GPU. Every tensor can be converted to GPU in order to perform massively parallel, fast computations. All operations that will be performed on the tensor will be carried out using GPU-specific routines that come with PyTorch.

If you don’t have access to a GPU, you can perform these examples on Google Colab. Select GPU as Runtime.

Let’s first see how to create a tensor for GPU.

In [19]:
# Create a tensor for CPU
# This will occupy CPU RAM
tensor_cpu = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], device='cpu')
 
# Create a tensor for GPU
# This will occupy GPU RAM
#tensor_gpu = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], device='cuda')

If you are using Google Colab, focus on the RAM consumption meter in the top right corner and you will see 
the GPU RAM consumption increase as soon as you create tensor_gpu.

Just like tensor creation, the operations performed for CPU and GPU tensors are also different and consume 
RAM corresponding to the device specified.

In [20]:
# This uses CPU RAM
tensor_cpu = tensor_cpu * 5
 
# This uses GPU RAM
# Focus on GPU RAM Consumption
# -- tensor_gpu = tensor_gpu * 5

INTRODUCTION TO PYTORCH
Introduction to Torch’s tensor library
All of deep learning is computations on tensors, which are generalizations of a matrix that can be indexed 
in more than 2 dimensions. We will see exactly what this means in-depth later. First, lets look what we can do with 
tensors.

In [21]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

Creating Tensors:
Tensors can be created from Python lists with the torch.Tensor() function.

In [22]:
# torch.tensor(data) creates a torch.Tensor object with the given data.
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

# Creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.tensor(M_data)
print(M)

# Create a 3D tensor of size 2x2x2.
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


What is a 3D tensor anyway? Think about it like this. If you have a vector, indexing into the vector gives you a scalar. If you have a matrix, indexing into the matrix gives you a vector. If you have a 3D tensor, then indexing into the tensor gives you a matrix!

A note on terminology: when I say “tensor” in this tutorial, it refers to any torch.Tensor object. Matrices and vectors are special cases of torch.Tensors, where their dimension is 1 and 2 respectively. When I am talking about 3D tensors, I will explicitly use the term “3D tensor”.

In [23]:
# Index into V and get a scalar (0 dimensional tensor)
print(V[0])
# Get a Python number from it
print(V[0].item())

# Index into M and get a vector
print(M[0])

# Index into T and get a matrix
print(T[0])

tensor(1.)
1.0
tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.]])


You can also create tensors of other datatypes. The default, as you can see, is Float. To create a tensor of integer types, try torch.LongTensor(). Check the documentation for more data types, but Float and Long will be the most common.

You can create a tensor with random data and the supplied dimensionality with torch.randn()

In [24]:
x = torch.randn((3, 4, 5))
print(x)

tensor([[[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002],
         [-0.6092, -0.9798, -1.6091, -0.7121,  0.3037],
         [-0.7773, -0.2515, -0.2223,  1.6871,  0.2284],
         [ 0.4676, -0.6970, -1.1608,  0.6995,  0.1991]],

        [[ 0.8657,  0.2444, -0.6629,  0.8073,  1.1017],
         [-0.1759, -2.2456, -1.4465,  0.0612, -0.6177],
         [-0.7981, -0.1316,  1.8793, -0.0721,  0.1578],
         [-0.7735,  0.1991,  0.0457,  0.1530, -0.4757]],

        [[-0.1110,  0.2927, -0.1578, -0.0288,  0.4533],
         [ 1.1422,  0.2486, -1.7754, -0.0255, -1.0233],
         [-0.5962, -1.0055,  0.4285,  1.4761, -1.7869],
         [ 1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]])


Operations with Tensors:
You can operate on tensors in the ways you would expect.

In [25]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])


In [26]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [27]:
torch.arange(1, 4)

tensor([1, 2, 3])

In [31]:
torch.arange(1, 2.5, 0.5)

tensor([1.0000, 1.5000, 2.0000])

In [32]:
torch.range(1, 4)

C:\Users\Eshwar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([1., 2., 3., 4.])

In [33]:
torch.range(1, 4, 0.5)

C:\Users\Eshwar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000])

In [40]:
torch.linspace(3, 10, steps=8)

tensor([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
torch.linspace(3, 10, steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [43]:
torch.linspace(-10, 10, steps=5)

tensor([-10.,  -5.,   0.,   5.,  10.])

In [44]:
torch.linspace(start=-10, end=10, steps=5)

tensor([-10.,  -5.,   0.,   5.,  10.])

In [46]:
torch.linspace(start=-10, end=10, steps=3)

tensor([-10.,   0.,  10.])

In [47]:
torch.logspace(start=-10, end=10, steps=5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.

In [53]:
# A 2-D tensor with ones on the diagonal and zeros elsewhere
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [54]:
torch.empty(2, 3)

tensor([[1.0000e+01, 5.0000e+00, 1.4013e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])

In [55]:
torch.empty((2,3), dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [56]:
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

In [57]:
x = torch.randn(2, 3)
x

tensor([[-0.8029,  0.2366,  0.2857],
        [ 0.6898, -0.6331,  0.8795]])

In [58]:
torch.cat((x, x, x), 0)

tensor([[-0.8029,  0.2366,  0.2857],
        [ 0.6898, -0.6331,  0.8795],
        [-0.8029,  0.2366,  0.2857],
        [ 0.6898, -0.6331,  0.8795],
        [-0.8029,  0.2366,  0.2857],
        [ 0.6898, -0.6331,  0.8795]])

In [59]:
torch.cat((x, x, x), 1)

tensor([[-0.8029,  0.2366,  0.2857, -0.8029,  0.2366,  0.2857, -0.8029,  0.2366,
          0.2857],
        [ 0.6898, -0.6331,  0.8795,  0.6898, -0.6331,  0.8795,  0.6898, -0.6331,
          0.8795]])

Splits a tensor into a specific number of chunks.

Last chunk will be smaller if the tensor size along the given dimension dim is not divisible by chunks.

In [61]:
t = torch.tensor([[1,2],[3,4]])
torch.gather(t, 1, torch.tensor([[0,0],[1,0]]))

tensor([[1, 1],
        [4, 3]])

torch.masked_select(input, mask, out=None) → Tensor
Returns a new 1-D tensor which indexes the input tensor according to the binary mask mask which is a ByteTensor.

The shapes of the mask tensor and the input tensor don’t need to match, but they must be broadcastable.

NOTE

The returned tensor does not use the same storage as the original tensor

In [63]:
x = torch.randn(3, 4)
x

tensor([[ 0.3133, -1.1352,  0.3773, -0.2824],
        [-2.5667, -1.4303,  0.5009,  0.5438],
        [-0.4057,  1.1341, -1.1115,  0.3501]])

In [64]:
mask = x.ge(0.5)
mask


tensor([[0, 0, 0, 0],
        [0, 0, 1, 1],
        [0, 1, 0, 0]], dtype=torch.uint8)

In [65]:
torch.masked_select(x, mask)

tensor([0.5009, 0.5438, 1.1341])

torch.narrow(input, dimension, start, length) → Tensor
Returns a new tensor that is a narrowed version of input tensor. The dimension dim is input from start to start + length. The returned tensor and input tensor share the same underlying storage.

Parameters
input (Tensor) – the tensor to narrow

dimension (int) – the dimension along which to narrow

start (int) – the starting dimension

length (int) – the distance to the ending dimension

In [68]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
torch.narrow(x, 0, 0, 2)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [69]:
torch.narrow(x, 1, 1, 2)

tensor([[2, 3],
        [5, 6],
        [8, 9]])

In [70]:
x = torch.randn(3, 2)
y = torch.ones(3, 2)
x

tensor([[-0.7703, -0.1473],
        [ 0.6272,  1.0935],
        [ 0.0939,  1.2381]])

In [71]:
torch.where(x > 0, x, y)

tensor([[1.0000, 1.0000],
        [0.6272, 1.0935],
        [0.0939, 1.2381]])

torch.normal()
torch.normal(mean, std, out=None) → Tensor
Returns a tensor of random numbers drawn from separate normal distributions whose mean and standard deviation are given.

The mean is a tensor with the mean of each output element’s normal distribution

The std is a tensor with the standard deviation of each output element’s normal distribution

The shapes of mean and std don’t need to match, but the total number of elements in each tensor need to be the same.

In [72]:
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([-0.3459,  2.4607,  2.4454,  3.8833,  4.4001,  5.1762,  7.3239,  8.0166,
         9.2268,  9.9467])

In [73]:
torch.normal(mean=0.5, std=torch.arange(1., 6.))

tensor([ 1.1592e+00, -2.6928e+00, -6.3062e-01, -1.1908e+01,  2.6626e-03])

Similar to the function above, but the standard-deviations are shared among all drawn elements.

Parameters
mean (Tensor) – the tensor of per-element means

std (float, optional) – the standard deviation for all distributions

out (Tensor, optional) – the output tensor

In [74]:
torch.normal(mean=torch.arange(1., 6.))

tensor([0.2787, 3.2708, 2.9980, 2.9048, 5.6016])

torch.rand(*sizes, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)[0,1)

The shape of the tensor is defined by the variable argument sizes.

In [75]:
torch.rand(4)

tensor([0.4830, 0.2296, 0.6789, 0.3075])

In [76]:
torch.rand(2,3)

tensor([[0.2652, 0.5283, 0.8619],
        [0.1483, 0.7348, 0.8212]])

In [77]:
# Returns a tensor filled with random integers generated uniformly between low (inclusive) and high (exclusive).

# The shape of the tensor is defined by the variable argument size.

torch.randint(3, 5, (3,))

tensor([4, 3, 3])

In [78]:
torch.randint(10, (2, 2))

tensor([[4, 8],
        [6, 5]])

In [79]:
torch.randint(3, 10, (2, 2))

tensor([[8, 4],
        [5, 6]])

In [80]:
torch.randn(4)

tensor([ 0.5308, -0.4645,  0.7340, -0.4394])

In [81]:
torch.randn(2,3)

tensor([[ 0.9255,  0.8003, -0.4376],
        [-0.4595,  1.5414,  1.5618]])

In [82]:
# Returns a random permutation of integers from 0 to n - 1.

torch.randperm(5)

tensor([0, 2, 3, 4, 1])

Quasi-random sampling
CLASS torch.quasirandom.SobolEngine(dimension, scramble=False, seed=None)[SOURCE]
The torch.quasirandom.SobolEngine is an engine for generating (scrambled) Sobol sequences. Sobol sequences are an example of low discrepancy quasi-random sequences.

This implementation of an engine for Sobol sequences is capable of sampling sequences up to a maximum dimension of 1111. It uses direction numbers to generate these sequences, and these numbers have been adapted from here.

References

Art B. Owen. Scrambling Sobol and Niederreiter-Xing points. Journal of Complexity, 14(4):466-489, December 1998.

I. M. Sobol. The distribution of points in a cube and the accurate evaluation of integrals. Zh. Vychisl. Mat. i Mat. Phys., 7:784-802, 1967.

In [83]:
soboleng = torch.quasirandom.SobolEngine(dimension=5)
soboleng.draw(3)

tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.7500, 0.2500, 0.7500, 0.2500, 0.7500],
        [0.2500, 0.7500, 0.2500, 0.7500, 0.2500]])

## Math operations:
Pointwise Ops

In [86]:
torch.abs(torch.tensor([-1, -2, 3]))

tensor([1, 2, 3])

In [94]:
a = torch.randn(4)
a
torch.acos(a)   # Returns a new tensor with the arccosine of the elements of input.

tensor([1.6625, 1.4318, 2.2545, 1.2613])

In [96]:
torch.add(a, 20)
torch.acos(a)  # Inverse cosine of a

tensor([1.6625, 1.4318, 2.2545, 1.2613])

In [99]:
a = torch.randn(4)
a

tensor([ 0.3865, -1.0245,  0.0842,  1.6088])

In [101]:
b = torch.randn(4,1)
b

tensor([[-1.1417],
        [ 0.1935],
        [-2.8692],
        [-1.5053]])

In [102]:
torch.add(a, 10, b)

tensor([[ -9.8082],
        [  2.5154],
        [-27.2826],
        [-17.0406]])

In [107]:
t = torch.randn(1, 3)
print(t)
t1 = torch.randn(3, 1)
print(t1)
t2 = torch.randn(1, 3)
print(t2)
torch.addcdiv(t, 0.1, t1, t2)

tensor([[-0.4478,  0.3282,  0.2667]])
tensor([[ 0.8473],
        [-0.1348],
        [ 0.6477]])
tensor([[-1.6412, -0.4636,  0.3857]])


tensor([[-0.4994,  0.1454,  0.4864],
        [-0.4395,  0.3573,  0.2318],
        [-0.4872,  0.1885,  0.4346]])

In [108]:
# Division - Divides each element of the input input with the scalar value and returns a new resulting tensor.
a = torch.randn(5)
print(a)
torch.div(a, 0.5)

tensor([ 1.1993,  1.8805, -0.9891,  1.1937, -1.0595])


tensor([ 2.3985,  3.7610, -1.9782,  2.3874, -2.1189])

Each element of the tensor input is divided by each element of the tensor other. 
The resulting tensor is returned. The shapes of input and other must be broadcastable.

In [109]:
a = torch.randn(4, 4)
a

tensor([[-2.4107, -1.2778, -0.0629, -1.2308],
        [-1.0655, -0.3865,  0.3782, -0.0698],
        [ 0.6936,  0.4195,  2.2524, -0.0802],
        [-1.3489, -0.8263,  0.2648, -1.3158]])

In [110]:
b = torch.randn(4)
b

tensor([ 0.1491, -1.5896,  0.9902,  0.4578])

In [111]:
torch.div(a, b)

tensor([[-16.1687,   0.8039,  -0.0635,  -2.6886],
        [ -7.1466,   0.2431,   0.3820,  -0.1526],
        [  4.6522,  -0.2639,   2.2746,  -0.1751],
        [ -9.0469,   0.5198,   0.2674,  -2.8743]])

In [112]:
# Computes the logarithmic derivative of the gamma function on input.
a = torch.tensor([1, 0.5])
a

tensor([1.0000, 0.5000])

In [113]:
torch.digamma(a)

tensor([-0.5772, -1.9635])

In [114]:
# Computes the error function of each element. 
torch.erf(torch.tensor([0, -1., 10.]))

tensor([ 0.0000, -0.8427,  1.0000])

In [117]:
# Returns a new tensor with the exponential of the elements minus 1 of input.

import math
torch.expm1(torch.tensor([0, math.log(2.)]))

tensor([0., 1.])

In [118]:
# Returns a new tensor with the floor of the elements of input, the largest integer less than or equal to each element.
a = torch.randn(4)
a

tensor([-0.7087,  0.7963, -0.6352, -0.6320])

In [119]:
torch.floor(a)

tensor([-1.,  0., -1., -1.])

In [122]:
# Returns a new tensor with the natural logarithm of the elements of input.
a = torch.randn(5)
a

tensor([-0.5948, -0.2995,  0.2623, -0.4467, -0.3013])

In [123]:
torch.log(a)

tensor([    nan,     nan, -1.3381,     nan,     nan])

In [126]:
# Returns a new tensor with the logarithm to the base 10 of the elements of input.
a = torch.rand(5)
a

tensor([0.2287, 0.5795, 0.6656, 0.9314, 0.2377])

In [127]:
torch.log10(a)

tensor([-0.6407, -0.2369, -0.1768, -0.0308, -0.6240])

In [128]:
# Returns a new tensor with the natural logarithm of (1 + input).
a = torch.randn(5)
a
torch.log1p(a)

tensor([ 0.6462,     nan, -2.9750,  0.3197,     nan])

In [129]:
# Returns a new tensor with the logarithm to the base 2 of the elements of input.
a = torch.rand(5)
torch.log2(a)

tensor([-2.6254, -0.5407, -3.2804, -3.5654, -4.3121])

In [130]:
# Multiplies each element of the input input with the scalar value and returns a new resulting tensor.
a = torch.randn(3)
torch.mul(a,100)

tensor([-56.6370, 131.2451,  52.2131])

Matrix Multiplication
Each element of the tensor input is multiplied by the corresponding element of the Tensor other. The resulting tensor is returned.

The shapes of input and other must be broadcastable.

In [131]:
a = torch.randn(4, 1)
b = torch.randn(1, 4)
torch.mul(a,b)

tensor([[-3.4871e-01, -1.6183e-01,  1.0741e-01, -3.7273e-04],
        [ 9.4097e-02,  4.3669e-02, -2.8983e-02,  1.0058e-04],
        [ 1.4921e+00,  6.9248e-01, -4.5960e-01,  1.5949e-03],
        [ 3.9734e-01,  1.8440e-01, -1.2239e-01,  4.2471e-04]])

In [134]:
# Returns a new tensor with the square-root of the elements of input.
a = torch.rand(4)
print(a)
torch.sqrt(a)

tensor([0.9312, 0.7788, 0.1070, 0.2503])


tensor([0.9650, 0.8825, 0.3272, 0.5003])

In [137]:
# Returns the indices of the minimum value of all elements in the input tensor.
a = torch.randn(4, 4)
print(a)
torch.argmin(a)

tensor([[ 0.9356, -0.8873,  0.5298,  0.2684],
        [ 0.3501, -0.2723,  1.0666, -0.8953],
        [-0.3329, -0.9173,  0.8372,  1.4950],
        [-0.8303, -1.9901, -0.8779,  0.2204]])


tensor(13)

Returns the indices of the minimum values of a tensor across a dimension.

This is the second value returned by torch.min(). See its documentation for the exact semantics of this method.

In [141]:
a = torch.randn(4, 4)
print(a)
torch.argmin(a, dim=1)

tensor([[ 0.6536,  1.0295, -0.4674,  1.2100],
        [-0.9293,  1.5965, -0.0352,  0.1928],
        [-0.1146,  0.4031,  0.7834,  1.6241],
        [-1.9684,  0.9299,  1.5981,  0.4262]])


tensor([2, 0, 0, 0])

In [ ]:
#   https://pytorch.org/docs/stable/torch.html

In [ ]:
Refer above URL for more exercises and syntax